#if !defined(SCRIPDEFINITIONS__INCLUDED_)
#define SCRIPDEFINITIONS__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define VIEW_SECTION_BEGIN      _T("BEGIN_VIEW_SECTION")
#define VIEW_SECTION_END        _T("END_VIEW_SECTION")
#define VIEW_SECTION_MOVE       _T("MOVE")
#define VIEW_SECTION_FLOATWND   _T("FLOATWND")
#define VIEW_SECTION_GRAPH      _T("GRAPHVIEW")
#define VIEW_SECTION_SHSTUDIO   _T("SHSTUDIOVIEW")


#endif // !defined(SCRIPDEFINITIONS__INCLUDED_)

