#ifndef IMAGEPROC_BASEDEF_INC
#define IMAGEPROC_BASEDEF_INC

#include <video\TVFrame.h>

#define INACTIVE_COLOR 127
#define INACTIVE_REPLACE_COLOR (INACTIVE_COLOR-1)
#define ACTIVE_COLOR   255
#define WHITE_COLOR    255
#define BLACK_COLOR      0
#define GRAYED_WHITE_COLOR    (INACTIVE_COLOR+20)
#define GRAYED_BLACK_COLOR    (INACTIVE_COLOR-20)

#endif
