#ifndef TVDB_GENERAL_SETTINGS_INCLUDED
#define TVDB_GENERAL_SETTINGS_INCLUDED

// OCR

/*
#define CHAR_MIN_HEIGHT 7
#define CHAR_MAX_HEIGHT 30
#define CHAR_MIN_WIDTH 3
#define CHAR_MAX_WIDTH 30

#define CHAR_MIN_AREA 20
#define CHAR_MAX_AREA 200
#define CHAR_MIN_DENSITY 0.20
#define CHAR_MAX_DENSITY 0.80
#define CHAR_MIN_XYRATIO 0.3
#define CHAR_MAX_XYRATIO 0.80
*/

#define CHAR_MIN_HEIGHT 10
#define CHAR_MAX_HEIGHT 60
#define CHAR_MIN_WIDTH 5
#define CHAR_MAX_WIDTH 60

#define CHAR_MIN_AREA 50
#define CHAR_MAX_AREA 800
#define CHAR_MIN_DENSITY 0.20
#define CHAR_MAX_DENSITY 1.00
#define CHAR_MIN_XYRATIO 0.15
#define CHAR_MAX_XYRATIO 1.40

#define CONOVOLUTION_PARAM 600

#define ZONE_MIN_AREA 90
#define ZONE_MAX_AREA 2000
#define ZONE_MIN_DENSITY 0.4
#define ZONE_MAX_DENSITY 1.0
#define ZONE_MIN_XYRATIO 2.4
#define ZONE_MAX_XYRATIO 7

// OCR_LINES
#define RECTANGLE_EXTRA_EDGES 3

#endif
