#pragma once

//typedef enum RELAY_EVENT
//{
//	PHIDGET_EVENT_UNKNOWN,
//	PHIDGET_EVENT_CHANGED_INPUT,
//	PHIDGET_EVENT_CHANGED_OUTPUT,
//	PHIDGET_EVENT_REQUESTED_CHANGE_OUTPUT
//} *LPRELAY_EVENT;
//
//typedef enum DIGITAL_TYPE{
//	DIGITAL_TYPE_UNKNOWN,
//	DIGITAL_TYPE_IN = 0x1,
//	DIGITAL_TYPE_OUT = DIGITAL_TYPE_IN << 1
//};